services:
  app:
    image: ancous1/ancous-app:1
    container_name: my-app-1
    ports:
      - "5000:5000"
    environment:
      DB_HOST: my-postgres-1
      DB_PORT: 5432
      DB_NAME: python_interview
      DB_USER: root
      DB_PASSWORD: 1975
      REDIS_HOST: my-redis-1
      REDIS_PORT: 6379
    networks:
      - app-network
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres
    container_name: my-postgres-1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1975
      POSTGRES_DB: python_interview
    volumes:
      - db-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis
    container_name: my-redis-1
    volumes:
      - redis-data:/data
#    ports:
#      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: my-nginx-1
    volumes:
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    ports:
      - "8000:80"
      - "443:443"
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  db-data:
  redis-data:
